In [10]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import  confusion_matrix, classification_report

from sklearn import datasets
from sklearn.model_selection import train_test_split

In [49]:
iris = datasets.load_iris()
X_train, X_test, Y_train, Y_test = train_test_split(iris.data, 
                                                    iris.target,
                                                    test_size=0.2)

In [50]:
model = LogisticRegression()

model.fit(X_train, Y_train);


D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [51]:
model.coef_, model.intercept_
model.p

(array([[ 0.38202893,  1.43319407, -2.16662357, -0.97488014],
        [ 0.3969653 , -1.56031054,  0.56182234, -1.31550783],
        [-1.51473437, -1.52269344,  2.27327392,  2.20794916]]),
 array([ 0.24376952,  0.98822227, -0.93352491]))

In [52]:
Y_pred = model.predict(X_train)
confusion_matrix(Y_train, Y_pred)

array([[44,  0,  0],
       [ 0, 35,  3],
       [ 0,  1, 37]], dtype=int64)

In [53]:
print(classification_report(Y_train, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        44
           1       0.97      0.92      0.95        38
           2       0.93      0.97      0.95        38

    accuracy                           0.97       120
   macro avg       0.97      0.96      0.96       120
weighted avg       0.97      0.97      0.97       120



In [54]:
Y_pred = model.predict(X_test)
confusion_matrix(Y_test, Y_pred)

array([[ 6,  0,  0],
       [ 0, 10,  2],
       [ 0,  0, 12]], dtype=int64)

In [55]:

print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.83      0.91        12
           2       0.86      1.00      0.92        12

    accuracy                           0.93        30
   macro avg       0.95      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30

